import express from "express";
import addShippingToOrder from "../../controller/orders/add-shipping-details-to-order.js";
import abandonCheckout from "../../controller/orders/abandon-checkout.js";
import cancelOrder from "../../controller/orders/cancel-order.js";
import createOrderFromCart from "../../controller/orders/create-order-from-cart.js";
import getLatestPendingOrder from "../../controller/orders/get-latest-pending-order.js";
import getOrdersByStore from "../../controller/orders/get-orders-by-store.js";
import getThisUsersOrders from "../../controller/orders/get-user-orders.js";
import getOrderTracking from "../../controller/orders/track-order.js";
import { isLoggedIn } from "../../middleware/isLoggedIn.js";
import isStoreStaff from "../../middleware/isStoreStaff.js";
import payfastCheckout from "../../controller/orders/payfast-checkout.js";
import { limiter } from "../../utils/limiter.js";
const router = express.Router();
router.post("/from-cart", limiter, isLoggedIn, createOrderFromCart);
router.get("/store/:store_id", isLoggedIn, isStoreStaff, getOrdersByStore);
router.get("/latest-pending", isLoggedIn, getLatestPendingOrder);
router.put("/:orderId/shipping", isLoggedIn, addShippingToOrder);
router.get("/user/:id", isLoggedIn, getThisUsersOrders);
router.get("/track/:id", isLoggedIn, getOrderTracking);
router.put("/cancel/:id", isLoggedIn, cancelOrder);
router.post("/:orderId/payfast-checkout", isLoggedIn, payfastCheckout);
router.post("/:orderId/abandon", isLoggedIn, abandonCheckout);
export { router };
